providers:
  vertex_ai:
    base_url: "https://us-central1-aiplatform.googleapis.com"
    headers:
      Authorization: "Bearer ${ACCESS_TOKEN}"
    models:
      embedding-gecko-001:
        type: embedding
        model_name: "projects/isdata-staging/locations/us-central1/models/textembedding-004"
        provider: vertex_ai