version: "3.9"
services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thisispostgres
      POSTGRES_DB: bluemvmt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: bluemvmt.postgres   
      DB_USER: postgres
      DB_PASSWORD: thisispostgres
      DB_NAME: bluemvmt
      LOG_LEVEL: INFO
      PORT: 8080
    command: ["poetry", "run", "uvicorn", "src.search_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  pgdata:
